server:
  port: 8484

external:
  api:
    contractorUrl: http://127.0.0.1:8485/renohome

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/renohomehome
    username: renohomehome
    password: renohomehome
  jpa:
    show-sql: true
  zipkin:
    base-url: http://127.0.0.1:9411